### ISSUE TITLE
Will no longer be updated to the Raku ecosystem

### ISSUE THREAD

**Issue by lizmat** [raku-community-modules/Math-Random#3]
Hello,

Thank you for the time and effort you have put in what is now the [Raku Programming Language](https://raku.org).  The language and its ecosystem are [moving forward](https://github.com/Raku/problem-solving/pull/318).

This means that these distributions:

- https://github.com/bluebear94/Math-Random
- https://github.com/bluebear94/Terminal-WCWidth

will no longer be checked for updates by the Raku ecosystem.

This means that you will need to move your module to the [zef ecosystem](https://deathbykeystroke.com/articles/20210120-faq-zef-ecosystem.html) on the next update you make to these distributions.  Otherwise your update will simply not be seen by the ecosystem.

If you are no longer interested in maintaining these distributions, you can have these distributions moved to [Raku Community Modules Adoption Center](https://github.com/raku-community-modules/), where members of the Raku Community will take care of them.

This can be as easy as confirming that in a response to this issue.

Again, thank you for your time and efforts!

On behalf of the Raku Steering Council,

Elizabeth Mattijsen

**Comment by bluebear94** [comment]
Thanks for reaching out to me. I’m open to having these modules be moved to the CMAC.

**Comment by lizmat** [comment]
Thanks for your reply!

I see that Terminal::WCWidth has open Pull Requests.

In that case it would be best to move the repository to raku-community-modules.

If that is ok with you, then there are two ways of doing that:

1. you give me maintain access to these repos, and I will then transfer them to raku-community-modules

2. I give you maintain access to raku-community-modules, so you can do the transfer yourself.

If either is too involved for you, then I'll just fork the repos into raku-community-modules and will transport the PRs manually.

**Comment by bluebear94** [comment]
> 1. you give me maintain access to these repos, and I will then transfer them to raku-community-modules

I’ve sent you an invite.

**Comment by lizmat** [comment]
Thanks.

But apparently I still have insufficient rights to do a transfer of the repo  :-(

**Comment by lizmat** [comment]
I've sent you an invite for rak-community-modules.  If you accept that, you should be able to transfer the repo yourself to it.

**Comment by lizmat** [comment]
Now updated in the Raku Ecosystem:

- [Math::Random](https://raku.land/zef:raku-community-modules/Math::Random)
- [Terminal::WCWidth](https://raku.land/zef:raku-community-modules/Terminal::WCWidth)

Thanks!
